name = "bh-je"
type = "webpack"
account_id = "ae2e2411fc6462d1dd8edf4182094548"
workers_dev = true
route = "cf-pages.bh.je/workers/*"
zone_id = "dfa347b3f48e6b18985741d39b265123"
webpack_config = "webpack.config.js"
